#!/usr/bin/env ruby

require_relative '../init'

require 'component_host'

ComponentHost.start('registration-component') do |host|
  registration_component_initiator = RegistrationComponent::Start.build
  host.register(registration_component_initiator)
end
